/* Generated by Opal 0.5.2 */
(function($opal) {
  var self = $opal.top, $scope = $opal, nil = $opal.nil, $breaker = $opal.breaker, $slice = $opal.slice, $module = $opal.module;
  $opal.add_stubs(['$inspect']);
  return (function($base) {
    var self = $module($base, 'Kernel');

    var def = self._proto, $scope = self._scope;
    def.$pretty_inspect = function() {
      var self = this;
      return self.$inspect();
    }
        ;$opal.donate(self, ["$pretty_inspect"]);
  })(self)
})(Opal);

//@ sourceMappingURL=/__opal_source_maps__/pp.js.map
;
