// Generated by CoffeeScript 1.3.3
var Opal, execSync, extension, extensions, version, _i, _len,
  _this = this;

version = '0.3.19';

extensions = ['.opal', '.rb'];

execSync = require('exec-sync');

Opal = require("./opal-" + version).Opal;

exports.Opal = Opal;

Opal.source = function() {
  return _this.source || (_this.source = require('fs').readFileSync("" + __dirname + "/opal-" + version + ".js").toString());
};

Opal.parse = function(filename) {
  return execSync("opal _" + version + "_ " + filename);
};

for (_i = 0, _len = extensions.length; _i < _len; _i++) {
  extension = extensions[_i];
  require.extensions[extension] = function(module, filename) {
    var content;
    content = "var Opal = require('opal').Opal;" + "Opal.require = require;" + Opal.parse(filename);
    return module._compile(content, filename);
  };
}
