// Generated by CoffeeScript 1.3.3
(function() {
  var extension, extensions, fs, parser, parserFile, source, sourceFile, vm, _i, _len,
    _this = this;

  sourceFile = "" + __dirname + "/../opal/opal.js";

  parserFile = "" + __dirname + "/../opal/opal-parser.js";

  extensions = ['.opal', '.rb'];

  fs = require('fs');

  source = fs.readFileSync(sourceFile).toString();

  parser = fs.readFileSync(parserFile).toString();

  vm = require('vm');

  vm.runInThisContext(source, sourceFile);

  vm.runInThisContext(parser, parserFile);

  Opal.parse = function(ruby, filename) {
    return Opal.Opal.Parser.$new().$parse(ruby, filename);
  };

  for (_i = 0, _len = extensions.length; _i < _len; _i++) {
    extension = extensions[_i];
    require.extensions[extension] = function(module, filename) {
      var ruby;
      ruby = fs.readFileSync("" + filename).toString();
      source = Opal.parse(ruby, filename);
      source = source.replace(/\/\/= require +(\.\/)?([^;\n]+)(;|\n)/g, function(_, lead, required, semicolon_or_return) {
        return "require(\"" + required + "\")" + semicolon_or_return;
      });
      return module._compile(source, filename);
    };
  }

}).call(this);
