// Generated by CoffeeScript 1.3.3
var compile, execSync, extension, extensions, version, _i, _len;

version = '0.3.19';

extensions = ['.opal', '.rb'];

execSync = require('exec-sync');

exports.Opal = require("./opal-" + version).Opal;

compile = function(filename) {
  console.info('loading: ' + filename);
  return execSync("opal _" + version + "_ " + filename);
};

for (_i = 0, _len = extensions.length; _i < _len; _i++) {
  extension = extensions[_i];
  require.extensions[extension] = function(module, filename) {
    var content;
    content = "var Opal = require('opal').Opal;" + "Opal.require = require;" + compile(filename);
    return module._compile(content, filename);
  };
}
